# Configuración principal del sistema hospitalario
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: hospital-api
  
  # Base de datos PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/hospital_db
    username: hospital_user
    password: hospital_pass
    driver-class-name: org.postgresql.Driver
    
  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
        
  # Jackson - Configuración de fechas
  jackson:
    time-zone: America/Lima
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
      
  # Email configuración
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:}
    password: ${EMAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
  # Cache
  cache:
    type: simple
    
# JWT Configuración
jwt:
  secret: ${JWT_SECRET:hospitalSecretKey2024SuperSecureKeyForJWTTokenGenerationAndValidation}
  expiration: 86400000 # 24 horas
  issuer: hospital-api
  token-prefix: "Bearer "
  header-name: Authorization

# Logging
logging:
  level:
    com.hospital.backend: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      
# OpenAPI Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  info:
    title: Hospital Management API
    description: Sistema Integral de Gestión Hospitalaria
    version: 1.0.0
    contact:
      name: Hospital API Team
      email: dev@hospital.com